# Nixpacks config for Railway (Node + build frontend + backend)
# https://nixpacks.com/docs/configuration

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
